sudo: false
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
notifications:
  email: false
before_install: pip install --upgrade pip
script: >-
  python3 create_HODL_address.py --priv_key cNxmxYnXjdH8j1JwumuSF5HtLpjSDHv7x4ZWUQSf16mF4RxaYFnt --lock 115 | grep -Fxq "Time-locked address: 2N38r136aKrPs6LQmKY1gE3gj85XX5Na4cJ"
